// -----------------------------------------------------------------------------
// SUNBLIX OFFICIAL PRICELIST 2026 DATABASE & CATALOG
// Extracted from "SUNBLIX Pricelist 2026.xlsx"
// PT. SUNBLIX ENERGI INDONESIA
// -----------------------------------------------------------------------------

export const SUNBLIX_TERMS_2026 = [
  'Harga katalog merupakan harga paket standar mencakup pengiriman dan instalasi untuk wilayah Jawa, Madura, dan Bali.',
  'Di luar wilayah Jawa, Madura, dan Bali dapat dikenakan penyesuaian biaya pengiriman material dan akomodasi teknis.',
  'Harga final dapat disesuaikan setelah site survey berdasarkan kondisi aktual rooftop dan kebutuhan konstruksi sipil.',
  'Skema Pembayaran Proyek: 50% DP Proyek; 40% Setelah Material Tiba di Lokasi; 10% Setelah Sistem PLTS Selesai Dibangun.',
  'Harga sudah termasuk PPN (atau disesuaikan faktur pajak) dan berlaku selama kurs tukar USD ke IDR stabil (maks. Rp18.200/USD).',
  'Garansi Resmi Komponen: Inverter 5 Tahun, Panel Surya 12 Tahun (Kinerja 25 Thn), PV Bracket 5 Tahun, Baterai Lithium 5 Tahun, Garansi Instalasi 1 Tahun.',
  'Monitoring performa sistem 24/7 didukung aplikasi smart cloud berbasis IoT smartphone.',
];

export const SUNBLIX_SIGNATORY_DEFAULT = {
  name: 'Warsa',
  title: 'Authorized Representative',
  company: 'PT. SUNBLIX ENERGI INDONESIA',
};

// -----------------------------------------------------------------------------
// BATTERY ADD-ON CATALOG (SHEET: BATTERY ADD-ON)
// -----------------------------------------------------------------------------
export const BATTERY_ADDONS = [
  {
    id: 'bat_wm_5',
    label: 'Wall Mounted 5 kWh (5.12 kWh)',
    type: 'Wall Mounted',
    nominalCapacity: '5 kWh',
    energyKwh: 5.12,
    spec: '51.2V 100Ah LiFePO4 Smart BMS',
    price: 20400000,
    code: '0240-BATTERY-LITHIUM - WALL MOUNTED 5.12KWH',
    desc: 'Battery Energy Storage Unit Wall-Mounted 5.12 kWh\nBrand: SUNBLIX / Deye | Konfigurasi: 51.2V 100Ah LiFePO4\nFitur: Smart BMS, High Cycle Life >6000 cycles, Communication CAN/RS485\nGaransi Resmi: 5 Tahun',
    brand: 'SUNBLIX',
    unit: 'Unit',
    notes: 'Garansi 5 Tahun',
  },
  {
    id: 'bat_wm_10',
    label: 'Wall Mounted 10 kWh (10.24 kWh)',
    type: 'Wall Mounted',
    nominalCapacity: '10 kWh',
    energyKwh: 10.24,
    spec: '51.2V 200Ah LiFePO4 Smart BMS',
    price: 39200000,
    code: '0240-BATTERY-LITHIUM - WALL MOUNTED 10.24KWH',
    desc: 'Battery Energy Storage Unit Wall-Mounted 10.24 kWh\nBrand: SUNBLIX / Deye | Konfigurasi: 51.2V 200Ah LiFePO4\nFitur: Dual Parallel Ready, Smart BMS, Fast Charge Support\nGaransi Resmi: 5 Tahun',
    brand: 'SUNBLIX',
    unit: 'Unit',
    notes: 'Garansi 5 Tahun',
  },
  {
    id: 'bat_rm_5',
    label: 'Rack Mounted 5 kWh (5.12 kWh)',
    type: 'Rack Mounted',
    nominalCapacity: '5 kWh',
    energyKwh: 5.12,
    spec: '51.2V 100Ah LiFePO4 Smart BMS',
    price: 18000000,
    code: '0240-BATTERY-LITHIUM - RACK MOUNTED 5.12KWH',
    desc: 'Battery Energy Storage Unit Rack-Mounted 5.12 kWh (Server Rack 19\")\nBrand: SUNBLIX / Deye | Konfigurasi: 51.2V 100Ah LiFePO4\nFitur: Standard 19\" Rack Fit, Modular Scalable, Smart BMS\nGaransi Resmi: 5 Tahun',
    brand: 'SUNBLIX',
    unit: 'Unit',
    notes: 'Garansi 5 Tahun',
  },
];

// -----------------------------------------------------------------------------
// QUICK COMPONENT TEMPLATES (UNTUK TAMBAH BARIS DENGAN HARGA ACUAN RESMI)
// -----------------------------------------------------------------------------
export const COMPONENT_TEMPLATES = [
  {
    id: 'bat_wm_5',
    label: '🔋 Baterai Wall Mounted 5.12 kWh — Rp 20.400.000',
    code: '0240-BATTERY-LITHIUM - WM 5.12KWH',
    desc: 'Battery Storage Wall-Mounted 5.12 kWh (51.2V 100Ah LiFePO4)\nSmart BMS, CAN/RS485 Communication Port, Ready Stock',
    brand: 'SUNBLIX',
    qty: 1,
    unit: 'Unit',
    unitPrice: 20400000,
    notes: 'Garansi 5 Tahun',
    batteryKwh: '5.12',
  },
  {
    id: 'bat_wm_10',
    label: '🔋 Baterai Wall Mounted 10.24 kWh — Rp 39.200.000',
    code: '0240-BATTERY-LITHIUM - WM 10.24KWH',
    desc: 'Battery Storage Wall-Mounted 10.24 kWh (51.2V 200Ah LiFePO4)\nSmart BMS, High Capacity Storage, Ready Stock',
    brand: 'SUNBLIX',
    qty: 1,
    unit: 'Unit',
    unitPrice: 39200000,
    notes: 'Garansi 5 Tahun',
    batteryKwh: '10.24',
  },
  {
    id: 'bat_rm_5',
    label: '🔋 Baterai Rack Mounted 5.12 kWh — Rp 18.000.000',
    code: '0240-BATTERY-LITHIUM - RM 5.12KWH',
    desc: 'Battery Storage Rack-Mounted 5.12 kWh (Standard 19\" Rack)\nModular Stackable, Smart BMS, Ready Stock',
    brand: 'SUNBLIX',
    qty: 1,
    unit: 'Unit',
    unitPrice: 18000000,
    notes: 'Garansi 5 Tahun',
    batteryKwh: '5.12',
  },
  {
    id: 'pv_mod_585',
    label: '☀️ Panel Surya LONGI 585 Wp Tier 1 — Rp 2.150.000',
    code: 'PV-MOD-585W - LONGI MONO PERC',
    desc: 'Modul Surya High Efficiency 585 Wp Mono-Facial Tier 1\nBloombergNEF Certified, Anti-PID, 3.2mm Tempered Glass',
    brand: 'LONGI Solar',
    qty: 1,
    unit: 'Modul',
    unitPrice: 2150000,
    notes: 'Garansi 12 Tahun',
  },
  {
    id: 'inv_deye_6k',
    label: '⚡ Inverter Deye Hybrid 6 kW 1-Phase — Rp 23.500.000',
    code: 'INV-HYB-6KW - DEYE 1-PHASE',
    desc: 'Smart Hybrid Solar Inverter 6 kW Low Voltage Single Phase\nDual MPPT, Smart Load, Zero Export, Wi-Fi Monitoring App',
    brand: 'DEYE',
    qty: 1,
    unit: 'Unit',
    unitPrice: 23500000,
    notes: 'Garansi 5 Tahun',
  },
  {
    id: 'inv_deye_8k',
    label: '⚡ Inverter Deye Hybrid 8 kW 1-Phase — Rp 29.800.000',
    code: 'INV-HYB-8KW - DEYE 1-PHASE',
    desc: 'Smart Hybrid Solar Inverter 8 kW Low Voltage Single Phase\nDual MPPT, Parallel Ready, Wi-Fi Monitoring App',
    brand: 'DEYE',
    qty: 1,
    unit: 'Unit',
    unitPrice: 29800000,
    notes: 'Garansi 5 Tahun',
  },
  {
    id: 'inv_deye_10k_3p',
    label: '⚡ Inverter Deye Hybrid 10 kW 3-Phase — Rp 38.500.000',
    code: 'INV-HYB-10KW - DEYE 3-PHASE',
    desc: 'Smart Hybrid Solar Inverter 10 kW Low Voltage Three Phase\nDual MPPT, 100% Unbalanced Output, Full Backup',
    brand: 'DEYE',
    qty: 1,
    unit: 'Unit',
    unitPrice: 38500000,
    notes: 'Garansi 5 Tahun',
  },
  {
    id: 'mat_mounting_cabling',
    label: '🔩 Paket Mounting Aluminium & Kabel Surya — Rp 14.500.000',
    code: 'MNT-AL6005-SET - MOUNTING & CABLING',
    desc: 'Rail Aluminium AL6005-T5 Anodized, Mid/End Clamps, L-Feet\nKabel Surya DC 1x4mm (100M) & Kabel AC 3x4mm (15M)\nBox Proteksi MCB DC, SPD Arrester & MCB AC',
    brand: 'SUNBLIX Mount',
    qty: 1,
    unit: 'Set',
    unitPrice: 14500000,
    notes: 'Garansi 5 Tahun',
  },
  {
    id: 'srv_epc_commissioning',
    label: '🛠️ Jasa Instalasi, Komisioning & SLO — Rp 12.500.000',
    code: 'SRV-INSTALL-EPC - COMMISIONING & SLO',
    desc: 'Jasa Pemasangan Tim Ahli Bersertifikat K3 & Electrical Safety\nUji Fungsi Sistem, Setting Inverter Deye Cloud, Asistensi SLO ESDM',
    brand: 'SUNBLIX EPC',
    qty: 1,
    unit: 'Job',
    unitPrice: 12500000,
    notes: 'Garansi 1 Tahun',
  },
  {
    id: 'custom_blank',
    label: '➕ Tambah Baris Manual (Custom Item)',
    code: 'ITEM-BARU - SPESIFIKASI',
    desc: 'Deskripsi detail material / spesifikasi komponen tambahan...',
    brand: 'SUNBLIX',
    qty: 1,
    unit: 'Pcs',
    unitPrice: 1000000,
    notes: 'Ready Stock',
  },
];

// Helper to generate package items breakdown matching total price
function buildPackageItems(name, kwp, panelsCount, inverterDesc, inverterKw, phase, totalPrice) {
  const panelPriceEach = 2150000;
  const totalPvPrice = panelsCount * panelPriceEach;
  
  // Calculate remaining for Inverter, Balance of System (BoS), and EPC Service
  const remaining = Math.max(0, totalPrice - totalPvPrice);
  const invPrice = Math.round(remaining * 0.42);
  const epcPrice = Math.round(remaining * 0.28);
  const bosPrice = remaining - invPrice - epcPrice;

  return [
    {
      id: '1',
      code: `PV-MOD-585W - ${panelsCount}X LONGI MONO-FACIAL`,
      desc: `Modul Surya High Efficiency 585 Wp (${panelsCount} Modul)\nBrand: LONGI Solar Tier 1 BloombergNEF Certified\nEstimasi Area Rooftop: ~${Math.round(panelsCount * 3.25)} m²\nGaransi: 12 Thn Produk, 25 Thn Performa Output Linear`,
      brand: 'LONGI Solar',
      qty: panelsCount,
      unit: 'Modul',
      unitPrice: panelPriceEach,
      notes: 'Garansi 12 Tahun',
    },
    {
      id: '2',
      code: `INV-HYB-${inverterKw}KW - DEYE SMART HYBRID (${phase.toUpperCase()})`,
      desc: `Smart Hybrid Solar Inverter ${inverterKw} kW (${phase})\nBrand: DEYE Solar Energy | Dual MPPT Controller\nFitur: Smart Load, Zero Export, Built-in Wi-Fi Logger Deye Cloud\nGaransi Resmi: 5 Tahun`,
      brand: 'DEYE',
      qty: 1,
      unit: 'Unit',
      unitPrice: invPrice,
      notes: 'Garansi 5 Tahun',
    },
    {
      id: '3',
      code: `BOS-MAT-PKG - MOUNTING AL6005 & CABLING DC/AC`,
      desc: `Paket Material Instalasi & Perlindungan Listrik:\n- Struktur Rangka Aluminium AL6005-T5 Anodized & Mid/End Clamps\n- Kabel Surya DC 1x4mm & Kabel Listrik AC SNI\n- Box Proteksi Lengkap (DC Breaker, AC Breaker, SPD Surge Arrester)`,
      brand: 'SUNBLIX',
      qty: 1,
      unit: 'Set',
      unitPrice: bosPrice,
      notes: 'Garansi 5 Tahun',
    },
    {
      id: '4',
      code: `SRV-INST-COMM - JASA INSTALASI, TESTING & COMMISSIONING`,
      desc: `Layanan EPC & Pemasangan Bersertifikat:\n- Instalasi Modul Atap & Jalur Kelistrikan Standar K3\n- Setup & Komisioning Inverter Deye Hybrid & IoT Cloud App\n- Free Maintenance & Monitoring Berkala 1 Tahun Pertama`,
      brand: 'SUNBLIX Pro',
      qty: 1,
      unit: 'Job',
      unitPrice: epcPrice,
      notes: 'Garansi 1 Tahun',
    },
  ];
}

// -----------------------------------------------------------------------------
// COMPLETE 17 PACKAGES FROM "PRICE LIST" SHEET IN SUNBLIX PRICELIST 2026.XLSX
// -----------------------------------------------------------------------------
export const SUNBLIX_OFFICIAL_PACKAGES_2026 = [
  // --- STANDARD+ (1 Phase, Inverter 6 kW) ---
  {
    id: 'std_234',
    category: 'STANDARD+',
    name: 'SUNBLIX 2.34',
    kwp: '2.34',
    batteryKwh: '5.12',
    inverterKw: '6',
    phase: '1 Phase',
    pvArea: '~13 m²',
    panels: '4 Modul (LONGI 585 Wp)',
    panelsCount: 4,
    price: 63500000,
    coverImage: '/asset/product_standard.jpg',
    sub: 'STANDARD+ • 4 Modul • Inverter 6 kW 1P • Rp 63.500.000',
  },
  {
    id: 'std_351',
    category: 'STANDARD+',
    name: 'SUNBLIX 3.51',
    kwp: '3.51',
    batteryKwh: '5.12',
    inverterKw: '6',
    phase: '1 Phase',
    pvArea: '~19 m²',
    panels: '6 Modul (LONGI 585 Wp)',
    panelsCount: 6,
    price: 74000000,
    coverImage: '/asset/product_standard.jpg',
    sub: 'STANDARD+ • 6 Modul • Inverter 6 kW 1P • Rp 74.000.000',
  },
  {
    id: 'std_468',
    category: 'STANDARD+',
    name: 'SUNBLIX 4.68',
    kwp: '4.68',
    batteryKwh: '5.12',
    inverterKw: '6',
    phase: '1 Phase',
    pvArea: '~26 m²',
    panels: '8 Modul (LONGI 585 Wp)',
    panelsCount: 8,
    price: 88600000,
    coverImage: '/asset/product_standard.jpg',
    sub: 'STANDARD+ • 8 Modul • Inverter 6 kW 1P • Rp 88.600.000',
  },
  {
    id: 'std_585',
    category: 'STANDARD+',
    name: 'SUNBLIX 5.85',
    kwp: '5.85',
    batteryKwh: '5.12',
    inverterKw: '6',
    phase: '1 Phase',
    pvArea: '~32 m²',
    panels: '10 Modul (LONGI 585 Wp)',
    panelsCount: 10,
    price: 101800000,
    coverImage: '/asset/product_standard.jpg',
    sub: 'STANDARD+ • 10 Modul • Inverter 6 kW 1P • Rp 101.800.000',
  },
  {
    id: 'std_702',
    category: 'STANDARD+',
    name: 'SUNBLIX 7.02',
    kwp: '7.02',
    batteryKwh: '5.12',
    inverterKw: '6',
    phase: '1 Phase',
    pvArea: '~39 m²',
    panels: '12 Modul (LONGI 585 Wp)',
    panelsCount: 12,
    price: 121600000,
    coverImage: '/asset/product_standard.jpg',
    sub: 'STANDARD+ • 12 Modul • Inverter 6 kW 1P • Rp 121.600.000',
  },

  // --- PRO (1 Phase, Inverter 8-12 kW) ---
  {
    id: 'pro_819',
    category: 'PRO',
    name: 'SUNBLIX 8.19',
    kwp: '8.19',
    batteryKwh: '10.24',
    inverterKw: '8',
    phase: '1 Phase',
    pvArea: '~45 m²',
    panels: '14 Modul (LONGI 585 Wp)',
    panelsCount: 14,
    price: 145400000,
    coverImage: '/asset/product_pro.jpg',
    sub: 'PRO • 14 Modul • Inverter 8 kW 1P • Rp 145.400.000',
  },
  {
    id: 'pro_936',
    category: 'PRO',
    name: 'SUNBLIX 9.36',
    kwp: '9.36',
    batteryKwh: '10.24',
    inverterKw: '8',
    phase: '1 Phase',
    pvArea: '~52 m²',
    panels: '16 Modul (LONGI 585 Wp)',
    panelsCount: 16,
    price: 158600000,
    coverImage: '/asset/product_pro.jpg',
    sub: 'PRO • 16 Modul • Inverter 8 kW 1P • Rp 158.600.000',
  },
  {
    id: 'pro_1053',
    category: 'PRO',
    name: 'SUNBLIX 10.53',
    kwp: '10.53',
    batteryKwh: '10.24',
    inverterKw: '10',
    phase: '1 Phase',
    pvArea: '~58 m²',
    panels: '18 Modul (LONGI 585 Wp)',
    panelsCount: 18,
    price: 185000000,
    coverImage: '/asset/product_pro.jpg',
    sub: 'PRO • 18 Modul • Inverter 10 kW 1P • Rp 185.000.000',
  },
  {
    id: 'pro_1170',
    category: 'PRO',
    name: 'SUNBLIX 11.70',
    kwp: '11.70',
    batteryKwh: '10.24',
    inverterKw: '12',
    phase: '1 Phase',
    pvArea: '~64 m²',
    panels: '20 Modul (LONGI 585 Wp)',
    panelsCount: 20,
    price: 204900000,
    coverImage: '/asset/product_pro.jpg',
    sub: 'PRO • 20 Modul • Inverter 12 kW 1P • Rp 204.900.000',
  },
  {
    id: 'pro_1404',
    category: 'PRO',
    name: 'SUNBLIX 14.04',
    kwp: '14.04',
    batteryKwh: '10.24',
    inverterKw: '12',
    phase: '1 Phase',
    pvArea: '~77 m²',
    panels: '24 Modul (LONGI 585 Wp)',
    panelsCount: 24,
    price: 244500000,
    coverImage: '/asset/product_pro.jpg',
    sub: 'PRO • 24 Modul • Inverter 12 kW 1P • Rp 244.500.000',
  },

  // --- PRO+ (3 Phase, Inverter 8-15 kW) ---
  {
    id: 'proplus_936',
    category: 'PRO+',
    name: 'SUNBLIX 9.36 (3P)',
    kwp: '9.36',
    batteryKwh: '10.24',
    inverterKw: '8',
    phase: '3 Phase',
    pvArea: '~52 m²',
    panels: '16 Modul (LONGI 585 Wp)',
    panelsCount: 16,
    price: 214100000,
    coverImage: '/asset/product_pro.jpg',
    sub: 'PRO+ • 16 Modul • Inverter 8 kW 3P • Rp 214.100.000',
  },
  {
    id: 'proplus_1053',
    category: 'PRO+',
    name: 'SUNBLIX 10.53 (3P)',
    kwp: '10.53',
    batteryKwh: '10.24',
    inverterKw: '10',
    phase: '3 Phase',
    pvArea: '~58 m²',
    panels: '18 Modul (LONGI 585 Wp)',
    panelsCount: 18,
    price: 227300000,
    coverImage: '/asset/product_pro.jpg',
    sub: 'PRO+ • 18 Modul • Inverter 10 kW 3P • Rp 227.300.000',
  },
  {
    id: 'proplus_1170',
    category: 'PRO+',
    name: 'SUNBLIX 11.70 (3P)',
    kwp: '11.70',
    batteryKwh: '10.24',
    inverterKw: '12',
    phase: '3 Phase',
    pvArea: '~64 m²',
    panels: '20 Modul (LONGI 585 Wp)',
    panelsCount: 20,
    price: 244500000,
    coverImage: '/asset/product_pro.jpg',
    sub: 'PRO+ • 20 Modul • Inverter 12 kW 3P • Rp 244.500.000',
  },
  {
    id: 'proplus_1287',
    category: 'PRO+',
    name: 'SUNBLIX 12.87 (3P)',
    kwp: '12.87',
    batteryKwh: '10.24',
    inverterKw: '12',
    phase: '3 Phase',
    pvArea: '~71 m²',
    panels: '22 Modul (LONGI 585 Wp)',
    panelsCount: 22,
    price: 257700000,
    coverImage: '/asset/product_pro.jpg',
    sub: 'PRO+ • 22 Modul • Inverter 12 kW 3P • Rp 257.700.000',
  },
  {
    id: 'proplus_1404',
    category: 'PRO+',
    name: 'SUNBLIX 14.04 (3P)',
    kwp: '14.04',
    batteryKwh: '10.24',
    inverterKw: '15',
    phase: '3 Phase',
    pvArea: '~77 m²',
    panels: '24 Modul (LONGI 585 Wp)',
    panelsCount: 24,
    price: 284200000,
    coverImage: '/asset/product_pro.jpg',
    sub: 'PRO+ • 24 Modul • Inverter 15 kW 3P • Rp 284.200.000',
  },
  {
    id: 'proplus_1521',
    category: 'PRO+',
    name: 'SUNBLIX 15.21 (3P)',
    kwp: '15.21',
    batteryKwh: '10.24',
    inverterKw: '15',
    phase: '3 Phase',
    pvArea: '~84 m²',
    panels: '26 Modul (LONGI 585 Wp)',
    panelsCount: 26,
    price: 297400000,
    coverImage: '/asset/product_pro.jpg',
    sub: 'PRO+ • 26 Modul • Inverter 15 kW 3P • Rp 297.400.000',
  },
  {
    id: 'proplus_1638',
    category: 'PRO+',
    name: 'SUNBLIX 16.38 (3P)',
    kwp: '16.38',
    batteryKwh: '10.24',
    inverterKw: '15',
    phase: '3 Phase',
    pvArea: '~90 m²',
    panels: '28 Modul (LONGI 585 Wp)',
    panelsCount: 28,
    price: 310600000,
    coverImage: '/asset/product_pro.jpg',
    sub: 'PRO+ • 28 Modul • Inverter 15 kW 3P • Rp 310.600.000',
  },
];

// Combine into dictionary of presets ready for quoteData
export function getPresetFromPackage(pkg, docNo = 'SBX/SPH/X/2026/001', sphCode = 'SPH 001', customer = 'Bapak/Ibu Pelanggan') {
  const kwpNum = parseFloat(pkg.kwp) || 2.5;
  return {
    id: pkg.id,
    label: `${pkg.name} (${pkg.kwp} kWp)`,
    sub: `${pkg.category} • ${pkg.panelsCount} Modul • ${pkg.phase} • Rp ${pkg.price.toLocaleString('id-ID')}`,
    docNo: docNo,
    sphCode: sphCode,
    date: '01 Oktober 2026',
    customer: customer,
    project: `PLTS Hybrid ${pkg.kwp} kWp (${pkg.name})`,
    delivery: 'Wilayah Jawa, Madura & Bali (Include Delivery)',
    phone: '0852 8858 1027',
    email: 'hello@sunblix.id',
    powerKwp: pkg.kwp,
    batteryKwh: pkg.batteryKwh,
    inverterKw: pkg.inverterKw,
    phase: pkg.phase,
    pvArea: pkg.pvArea,
    panels: pkg.panels,
    estMonthlyKwh: Math.round(kwpNum * 125),
    estMonthlySavings: Math.round(kwpNum * 125 * 1444),
    estCo2Kg: Math.round(kwpNum * 110),
    coverImage: pkg.coverImage,
    items: buildPackageItems(
      pkg.name,
      pkg.kwp,
      pkg.panelsCount,
      `DEYE ${pkg.inverterKw} kW`,
      pkg.inverterKw,
      pkg.phase,
      pkg.price
    ),
    notes: SUNBLIX_TERMS_2026,
    signatory: SUNBLIX_SIGNATORY_DEFAULT,
  };
}
